apiVersion: v1
kind: Service
metadata:
  name: mnist-classifier-service
  labels:
    app: mnist-classifier
spec:
  type: LoadBalancer
  selector:
    app: mnist-classifier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
